package io.liquichain.api.payment;

import java.util.*;

import org.meveo.admin.exception.BusinessException;
import org.meveo.service.script.Script;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MolliePaymentScript extends Script {
    private static final Logger LOG = LoggerFactory.getLogger(MolliePaymentScript.class);

    private String result;
    private String method = null;

    public String getResult() {
        return result;
    }

    public void setMethod(String method) {
        LOG.info("method setter {}", method);
        this.method = method;
    }

    public String getMethod() {
        return method;
    }

    @Override
    public void execute(Map<String, Object> parameters) throws BusinessException {
        LOG.info("method from path={}", getMethod());
        result = "{\r\n"
            + "    \"count\": 2,\r\n"
            + "    \"_embedded\": {\r\n"
            + "        \"methods\": [\r\n"
            + "            {\r\n"
            + "                 \"resource\": \"method\",\r\n"
            + "                 \"id\": \"licoin\",\r\n"
            + "                 \"description\": \"Licoin\",\r\n"
            + "                 \"minimumAmount\": {\r\n"
            + "                     \"value\": \"0.01\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"maximumAmount\": {\r\n"
            + "                     \"value\": \"50000.00\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"image\": {\r\n"
            + "                     \"size1x\": \"https://docs.liquichain.io/media/payments/licoin.png\",\r\n"
            + "                     \"size2x\": \"https://docs.liquichain.io/media/payments/licoin%402x.png\",\r\n"
            + "                     \"svg\": \"https://docs.liquichain.io/media/payments/licoin.svg\"\r\n"
            + "                 },\r\n"
            + "                 \"status\": \"activated\",\r\n"
            + "                 \"pricing\": [\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"Netherlands\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.29\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"0\"\r\n"
            + "                     }\r\n"
            + "                 ],\r\n"
            + "                 \"_links\": {\r\n"
            + "                     \"self\": {\r\n"
            + "                         \"href\": \"https://liquichain.io/meveo/rest/gp/v1/methods/licoin\",\r\n"
            + "                         \"type\": \"application/hal+json\"\r\n"
            + "                     }\r\n"
            + "                 }\r\n"
            + "            },\r\n"
            + "            {\r\n"
            + "                 \"resource\": \"method\",\r\n"
            + "                 \"id\": \"creditcard2\",\r\n"
            + "                 \"description\": \"Credit card\",\r\n"
            + "                 \"minimumAmount\": {\r\n"
            + "                     \"value\": \"0.01\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"maximumAmount\": {\r\n"
            + "                     \"value\": \"2000.00\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"image\": {\r\n"
            + "                     \"size1x\": \"https://docs.liquichain.io/media/payments/creditcard.png\",\r\n"
            + "                     \"size2x\": \"https://docs.liquichain.io/media/payments/creditcard%402x.png\",\r\n"
            + "                     \"svg\": \"https://docs.liquichain.io/media/payments/creditcard.svg\"\r\n"
            + "                 },\r\n"
            + "                 \"status\": \"activated\",\r\n"
            + "                 \"pricing\": [\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"Commercial & non-European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"other\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"1.8\",\r\n"
            + "                         \"feeRegion\": \"eu-cards\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"American Express\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"amex\"\r\n"
            + "                     }\r\n"
            + "                 ],\r\n"
            + "                 \"_links\": {\r\n"
            + "                     \"self\": {\r\n"
            + "                         \"href\": \"https://liquichain.io/meveo/rest/gp/v1/methods/creditcard\",\r\n"
            + "                         \"type\": \"application/hal+json\"\r\n"
            + "                     }\r\n"
            + "                 }\r\n"
            + "            },\r\n"
            + "            {\r\n"
            + "                 \"resource\": \"method\",\r\n"
            + "                 \"id\": \"playCoin\",\r\n"
            + "                 \"description\": \"Play coin\",\r\n"
            + "                 \"minimumAmount\": {\r\n"
            + "                     \"value\": \"0.01\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"maximumAmount\": {\r\n"
            + "                     \"value\": \"2000.00\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"image\": {\r\n"
            + "                     \"size1x\": \"https://docs.liquichain.io/media/payments/creditcard.png\",\r\n"
            + "                     \"size2x\": \"https://docs.liquichain.io/media/payments/creditcard%402x.png\",\r\n"
            + "                     \"svg\": \"https://docs.liquichain.io/media/payments/creditcard.svg\"\r\n"
            + "                 },\r\n"
            + "                 \"status\": \"activated\",\r\n"
            + "                 \"pricing\": [\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"Commercial & non-European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"other\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"1.8\",\r\n"
            + "                         \"feeRegion\": \"eu-cards\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"American Express\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"amex\"\r\n"
            + "                     }\r\n"
            + "                 ],\r\n"
            + "                 \"_links\": {\r\n"
            + "                     \"self\": {\r\n"
            + "                         \"href\": \"https://liquichain.io/meveo/rest/gp/v1/methods/creditcard\",\r\n"
            + "                         \"type\": \"application/hal+json\"\r\n"
            + "                     }\r\n"
            + "                 }\r\n"
            + "            },\r\n"
            + "            {\r\n"
            + "                 \"resource\": \"method\",\r\n"
            + "                 \"id\": \"klubcoin\",\r\n"
            + "                 \"description\": \"Klub coin\",\r\n"
            + "                 \"minimumAmount\": {\r\n"
            + "                     \"value\": \"0.01\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"maximumAmount\": {\r\n"
            + "                     \"value\": \"2000.00\",\r\n"
            + "                     \"currency\": \"EUR\"\r\n"
            + "                 },\r\n"
            + "                 \"image\": {\r\n"
            + "                     \"size1x\": \"https://docs.liquichain.io/media/payments/creditcard.png\",\r\n"
            + "                     \"size2x\": \"https://docs.liquichain.io/media/payments/creditcard%402x.png\",\r\n"
            + "                     \"svg\": \"https://docs.liquichain.io/media/payments/creditcard.svg\"\r\n"
            + "                 },\r\n"
            + "                 \"status\": \"activated\",\r\n"
            + "                 \"pricing\": [\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"Commercial & non-European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"other\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"European cards\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"1.8\",\r\n"
            + "                         \"feeRegion\": \"eu-cards\"\r\n"
            + "                     },\r\n"
            + "                     {\r\n"
            + "                         \"description\": \"American Express\",\r\n"
            + "                         \"fixed\": {\r\n"
            + "                             \"value\": \"0.25\",\r\n"
            + "                             \"currency\": \"EUR\"\r\n"
            + "                         },\r\n"
            + "                         \"variable\": \"2.8\",\r\n"
            + "                         \"feeRegion\": \"amex\"\r\n"
            + "                     }\r\n"
            + "                 ],\r\n"
            + "                 \"_links\": {\r\n"
            + "                     \"self\": {\r\n"
            + "                         \"href\": \"https://liquichain.io/meveo/rest/gp/v1/methods/creditcard\",\r\n"
            + "                         \"type\": \"application/hal+json\"\r\n"
            + "                     }\r\n"
            + "                 }\r\n"
            + "            }\r\n"
            + "        ]\r\n"
            + "    },\r\n"
            + "    \"_links\": {\r\n"
            + "        \"self\": {\r\n"
            + "            \"href\": \"https://liquichain.io/meveo/rest/gp/v1/methods\",\r\n"
            + "            \"type\": \"application/hal+json\"\r\n"
            + "        },\r\n        \"documentation\": {\r\n"
            + "            \"href\": \"https://docs.liquichain.com/reference/v2/methods-api/list-methods\",\r\n"
            + "            \"type\": \"text/html\"\r\n"
            + "        }\r\n"
            + "    }\r\n}";
    }

}
